---
  - name: Update apt-get cache (apt-get update)
    apt: update_cache=yes

  - name: Upgrade packages (full upgrade)
    apt: upgrade=dist

  - name: install required packages (apt)
    action: apt pkg={{ item }} state=installed
    with_items:
      - python
      - wireshark
      - traceroute
      - zerofree
      - python-pip

  - name: Create workspace directory
    file: path=/home/user/workspace state=directory mode=0755

  - name: Include Dreamer-Management-Scripts
    include: Dreamer-Management-Scripts.yml

  - name: Include dreamer-ryu
    include: dreamer-ryu.yml

  - name: Include Dreamer-Topology-Parser
    include: Dreamer-Topology-Parser.yml

  - name: Include Dreamer-Mininet-Extensions
    include: Dreamer-Mininet-Extensions.yml
