---
  - name: Update apt-get cache (apt-get update)
  - apt: update_cache=yes

  - name: Upgrade packages (full upgrade)
  - apt: upgrade=dist

  - name: Install Python (2.x in ubuntu 15.10)
  - apt: name=python

  - name: Install Wireshark
  - apt: name=wireshark

  - name: Install traceroute
  - apt: name=traceroute

  - name: Install zerofree
  - apt: name=zerofree
