---
  - name: Ensure user exists
    user: name=user
          home=/home/user
          state=present

  - name: install required packages (apt)
    action: apt pkg={{ item }} state=installed
    with_items:
      - python
      - wireshark
      - traceroute
      - zerofree
      - python-pip
      - nano
      - git
      - python-dev
      - sshpass
      
  - name: Create workspace directory
    file: path=/home/user/workspace state=directory mode=0755

  - name: Clone REPOs
    git: repo={{ item.url }} dest={{ item.destination }}
    with_items:
      - { url: 'https://github.com/floodlight/floodlight.git', destination: '/home/user/workspace/floodlight-0.90' }
      - { url: 'https://github.com/netgroup/Mantoo-scripts-and-readme.git', destination: '/home/user/workspace/Mantoo-scripts-and-readme' }
      - { url: 'https://github.com/netgroup/dreamer-ryu.git', destination: '/home/user/workspace/dreamer-ryu' }
      - { url: 'https://github.com/netgroup/Dreamer-Topology-Parser.git', destination: '/home/user/workspace/Dreamer-Topology-Parser' }
      - { url: 'https://github.com/netgroup/SDN-TE-SR-tools.git', destination: '/home/user/workspace/SDN-TE-SR-tools' }
      - { url: 'https://github.com/netgroup/Dreamer-Experiment-Handler.git', destination: '/home/user/workspace/Dreamer-Experiment-Handler' }
      - { url: 'https://github.com/netgroup/Dreamer-Topology3D.git', destination'/home/user/workspace/Dreamer-Topology3D' }
      
  - name: Include Dreamer-Management-Scripts
    include: Dreamer-Management-Scripts.yml

  - name: Include Mininet
    include: Mininet.yml

  - name: Include Dreamer-Mininet-Extensions
    include: Dreamer-Mininet-Extensions.yml

  - name: Include Dreamer-Measurements-Tools
    include: Dreamer-Measurements-Tools.yml

  - name: Include Dreamer-Topology-and-Service-Validator
    include: Dreamer-Topology-and-Service-Validator.yml

  - name: Include Dreamer-Testbed-Deployer
    include: Dreamer-Testbed-Deployer.yml

  - name: Include OSHI-monitoring
    include: OSHI-monitoring.yml

  - name: Include OSHI-REST-server
    include: OSHI-REST-server.yml
