---
  - name: Ensure user exists
    user: name=user
          home=/home/user
          state=present

  - name: install required packages (apt)
    action: apt pkg={{ item }} state=installed
    with_items:
      - python
      - wireshark
      - traceroute
      - zerofree
      - python-pip
      - nano
      - git
      - python-dev
      - sshpass
      - lxde
      
  - name: Create workspace directory
    file: path=/home/user/workspace state=directory mode=0755

  - name: Clone Mantoo-scripts-and-readme repo
    git: repo=https://github.com/netgroup/Mantoo-scripts-and-readme.git dest=/home/user/workspace/Mantoo-scripts-and-readme

  - name: Clone dreamer-ryu repo
    git: repo=https://github.com/netgroup/dreamer-ryu.git dest=/home/user/workspace/dreamer-ryu  

  - name: Clone Dreamer-Topology-Parser repo
    git: repo=https://github.com/netgroup/Dreamer-Topology-Parser.git dest=/home/user/workspace/Dreamer-Topology-Parser

  - name: Clone SDN-TE-SR-tools repo
    git: repo=https://github.com/netgroup/SDN-TE-SR-tools.git dest=/home/user/workspace/SDN-TE-SR-tools

  - name: Clone Dreamer-Experiment-Handler repo
    git: repo=https://github.com/netgroup/Dreamer-Experiment-Handler.git dest=/home/user/workspace/Dreamer-Experiment-Handler

  - name: Clone Dreamer-Topology3D repo
    git: repo=https://github.com/netgroup/Dreamer-Topology3D.git dest=/home/user/workspace/Dreamer-Topology3D
      
  - name: Include Dreamer-Management-Scripts
    include: Dreamer-Management-Scripts.yml

  - name: Include Mininet
    include: Mininet.yml

  - name: Include Dreamer-Mininet-Extensions
    include: Dreamer-Mininet-Extensions.yml

  - name: Include Dreamer-Measurements-Tools
    include: Dreamer-Measurements-Tools.yml

  - name: Include Dreamer-Topology-and-Service-Validator
    include: Dreamer-Topology-and-Service-Validator.yml

  - name: Include Dreamer-Testbed-Deployer
    include: Dreamer-Testbed-Deployer.yml

  - name: Include OSHI-monitoring
    include: OSHI-monitoring.yml

  - name: Include OSHI-REST-server
    include: OSHI-REST-server.yml

  - name: Set ownership of /home/user to user
    file: path=/home/user recurse=yes owner=user group=user
