---
  - name: Clone Mininet
    git: repo=https://github.com/mininet/mininet.git dest=/home/user/workspace/mininet version=aae0affae46a63ef5e54d86351c96417c3888112

  - name: Install Mininet
    command: /home/user/workspace/mininet/util/install.sh -ent
    args:
      chdir: /home/user/workspace
      creates: /usr/local/bin/mn
