---
  - name: Clone OSHI-monitoring
    git: repo=https://github.com/netgroup/OSHI-monitoring.git dest=/home/user/workspace

  - name: install required packages (apt)
    action: apt pkg={{ item }} state=installed
    with_items:
      - rrdtool
      - librrds-perl
      - librrd-dev

  - name: Install rrdtool (pip)
    pip: name=rrdtool
