VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box='netgroup/oshi'

  config.vm.hostname='oshi'

  config.vm.network "forwarded_port", guest: 9200, host: 9200 # ElasticSearch
  config.vm.network "forwarded_port", guest: 5000, host: 5000 # Logstash
  config.vm.network "forwarded_port", guest: 80, host: 8080 # nginx
  config.vm.network "forwarded_port", guest: 5601, host: 5601 # Kibana
  
  config.vm.provider "virtualbox" do |v|
    host = RbConfig::CONFIG['host_os']

    # Give VM 1/2 system memory & access to all cpu cores on the host
    if host =~ /darwin/
      cpus = `sysctl -n hw.ncpu`.to_i
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024 / 1024 / 2
    elsif host =~ /linux/
      cpus = `nproc`.to_i
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 2
    else # sorry Windows folks, I can't help you
      cpus = 2
      mem = 512
    end

    v.customize ["modifyvm", :id, "--memory", mem]
    v.customize ["modifyvm", :id, "--cpus", cpus]
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    # 10 MB is the minimum to enable Virtualbox seamless mode
    v.customize ["modifyvm", :id, "--vram", "10"]
  end

  config.ssh.username="user"

  # Fix for stdin: is no a tty. See issue #1673 on mitchellh/vagrant on GitHub
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

end
