---
  - hosts: all
    gather_facts: yes
    pre_tasks:
      - name: Upgrade apt packages
        become: yes
        apt: upgrade=dist update_cache=yes cache_valid_time=300
    roles:
      - oshi
      - { role: geerlingguy.elasticsearch, become: yes, java_packages: ['openjdk-8-jdk'] }
      - { role: geerlingguy.logstash, become: yes, logstash_monitor_local_syslog: false }
      - { role: geerlingguy.nginx, become: yes }
      - { role: geerlingguy.kibana, become: yes }
