---
  - hosts: all
    gather_facts: yes
    tasks:
      - name: Install Vagrant insecure keypair
        become: true
        authorized_key: user=user key=https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub
