---
- name: Ensure htpasswd-related utilities are installed (Debian).
  apt: "pkg={{ item }} state=present"
  with_items:
    - apache2-utils
    - python-passlib
  when: ansible_os_family == 'Debian'


- name: Download Kibana.
  get_url:
    url: "https://download.elastic.co/kibana/kibana/kibana-4.4.0-linux-x64.tar.gz"
    dest: "{{ workspace }}/kibana-4.4.0-linux-x64.tar.gz"

- name: Expand Kibana.
  command: >
    tar -C {{ workspace }} -xvzf {{ workspace }}/kibana-4.4.0-linux-x64.tar.gz
    creates={{ kibana_root }}/config.js

- name: Ensure www directory exists.
  file:
    path: /var/www
    state: directory

- name: Move Kibana in www directory
  command: >
    mv {{ workspace }}/kibana-4.4.0-linux-x64 {{ kibana_root }}
    creates={{ kibana_root }}/config.js

- name: Copy Kibana configuration.
  template:
    src: config.js.j2
    dest: "{{ kibana_root }}/config.js"
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Copy Kibana nginx configuration.
  template:
    src: kibana.conf.j2
    dest: /etc/nginx/conf.d/kibana.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: Create Kibana user account.
  htpasswd:
    path: /etc/nginx/conf.d/kibana.htpasswd
    name: "{{ kibana_username }}"
    password: "{{ kibana_password }}"
    owner: root
    group: "{{ nginx_user }}"
    mode: 0640
  notify: restart nginx
