---
- name: Add Kibana repository (cannot use the apt_repository task according to docs)
  command: echo "deb http://packages.elastic.co/kibana/4.4/debian stable main" | sudo tee -a /etc/apt/sources.list

- name: Update apt cache if repository just added.
  apt: update_cache=yes

- name: Install Kibana.
  apt: pkg=kibana state=present

- name: Ensure Kibana is started and enabled on boot.
  service: "name=kibana state=started enabled=true"
  